spring:
  application:
    name: collector
  jackson:
    default-property-inclusion: non_null

server:
  port: 8080

kafka:
  bootstrap-servers: localhost:9092
  topics:
    sensors: telemetry.sensors.v1
    hubs: telemetry.hubs.v1

logging:
  level:
    ru.yandex.practicum: DEBUG
    org.apache.kafka: INFO
    org.springframework.web: DEBUG