spring:
  application:
    name: aggregator

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: aggregator-group
  topics:
    sensors: telemetry.sensors.v1
    snapshots: telemetry.snapshots.v1

logging:
  level:
    ru.yandex.practicum: DEBUG
    org.apache.kafka: INFO
grpc:
  client:
    hub-router:
      address: 'static://localhost:59091'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext