spring:
  application:
    name: analyzer

  datasource:
    url: jdbc:postgresql://localhost:5432/analyzer
    username: analyzer
    password: analyzer
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop  # create-drop, update, validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    snapshot:
      group-id: analyzer-snapshot-group
    hub:
      group-id: analyzer-hub-group
  topics:
    snapshots: telemetry.snapshots.v1
    hubs: telemetry.hubs.v1

grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

logging:
  level:
    ru.yandex.practicum: DEBUG
    org.springframework: INFO
    org.hibernate: INFO
    org.apache.kafka: INFO